### ISSUE TITLE
Missing pthread flag

### ISSUE THREAD

**Issue by annaborn** [orocos-toolchain/utilmm#6]
[100%] Linking CXX executable utilmm_testsuite
    ../src/libutilmm.so.1.1: error: undefined reference to 'pthread_mutexattr_init'
    ../src/libutilmm.so.1.1: error: undefined reference to 'pthread_mutexattr_settype'
    ../src/libutilmm.so.1.1: error: undefined reference to 'pthread_mutexattr_destroy'
    collect2: error: ld returned 1 exit status

**Comment by doudou** [comment]
Oh man. Anyone still using this ?

**Comment by annaborn** [comment]
ConfigurationFinder from utilmm is used in one of environment models.

**Comment by doudou** [comment]
Could you propose a PR to fix this ?
